In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

We can create a Square root of each and every functions.

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

Can create exponential functions of an array

In [10]:
A = np.random.randn(10)
B = np.random.randn(10)
A

array([-0.22319427,  0.14886917, -0.02480971, -1.16267874, -0.15157015,
       -1.36122003, -1.36816673,  0.72090108, -0.54054346, -0.40580054])

A normal distrubution of some random numbers

In [11]:
# Binary functions

In [12]:
np.add(A, B)

array([ -3.92118597e-01,   1.89131917e-04,  -5.23896769e-01,
        -5.96785074e-01,  -5.53101320e-01,  -4.86243997e-01,
        -5.05266495e-01,  -2.20245672e+00,  -1.40571478e+00,
         1.34485514e+00])

In [13]:
np.maximum(A,B)

array([-0.16892433,  0.14886917, -0.02480971,  0.56589367, -0.15157015,
        0.87497604,  0.86290024,  0.72090108, -0.54054346,  1.75065568])

Will find maximum of 2 arrays in this matrix

In [14]:
website = 'https://www.facebook.com/'
import webbrowser
webbrowser.open(website)

True

We can check out the documentation of the Universal function here for numpy
